### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by Xhonor** [Namoshek/laravel-scout-database#37]
I install this package and use it in Orchid Admin platform. https://orchid.software/ru/docs/global-search/

And i have this error if i use search:

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`documents_in_index` as (select `document_type`, COUNT(DISTINCT(document_id)) as' at line 1 (SQL: with `documents_in_index` as (select `document_type`, COUNT(DISTINCT(document_id)) as cnt from `scout_index` where document_type = 'analytics_industry' group by `document_type`), `document_index` as (select `id`, `document_id`, `term`, `length`, `num_hits` from `scout_index` where document_type = 'analytics_industry'), `matching_terms` as ((select '0' as term, 0 as length from `document_index` where 0 = 1) union (select DISTINCT(term) as term, 1 as length from `document_index` where `term` like f%)), `term_frequency` as (select `term`, SUM(num_hits) as occurrences from `document_index` where `term` in (select `term` from `matching_terms`) group by `term`), `matches_with_score` as (select `di`.`document_id`, `di`.`term`, CASE WHEN mt.term IS NOT NULL THEN ((1 + LOG(1 * (CAST((SELECT cnt FROM documents_in_index) as float) / ((CASE WHEN tf.occurrences > 1 THEN tf.occurrences ELSE 1 END) + 1))))* ((1 * SQRT(CAST(di.num_hits as float)))+ (1 * SQRT(1.0 / (ABS(di.length - mt.length) + 1))))) ELSE 0 END as score from `document_index` as `di` inner join `term_frequency` as `tf` on `tf`.`term` = `di`.`term` left join `matching_terms` as `mt` on `mt`.`term` = `di`.`term`) select `document_id` from `matches_with_score` group by `document_id` order by SQRT(COUNT(DISTINCT(term))) * SUM(score) DESC, document_id ASC limit 15 offset 0)

What is the problem? How to fix this? I forgot something?

**Comment by Namoshek** [comment]
Can you please let me know which versions of Laravel, Scout and MySql you are using?

**Comment by Xhonor** [comment]
Laravel 8;
Mysql: mysql  Ver 14.14 Distrib 5.7.30, for Linux (x86_64) using  EditLine wrapper
Scout: "laravel/scout": "^9.4",

**Comment by Namoshek** [comment]
I'm afraid the package is not compatible with MySQL 5.7 because it makes use of Common Table Expressions in the query. The supported database systems are outlined by [`staudenmeir/laravel-cte`](https://github.com/staudenmeir/laravel-cte).

**Comment by umefarooq** [comment]
I am facing same issue i have laravel 11, php 8.2 and mysql version 5.7.23-23, as you mentioned this package dose not support mysql 5.7 what is the solution for this now? I am using managed web hosting it is not VPS or cloud server

**Comment by Namoshek** [comment]
There is no solution. It is simply not supported due to technical reasons. Looking at the [end of life date for MySql 5.7](https://endoflife.date/mysql), you really should not be using it anymore.
